= Springlets image:https://travis-ci.org/DISID/springlets.svg?branch=master["Build Status", link="https://travis-ci.org/DISID/springlets"]

Springlets provides a series of heterogeneus utilities and Spring Boot starters not currently available in the Spring projects like Spring Framework, Spring Data or Spring Boot, as well as other open source projects used in Java web projects.

Our goal in Springlets is to follow the conventions used in the Spring projects (naming, versioning, project structure, ...) as close as possible. As a matter of fact, you can easily view to which Spring project are related most Springlet modules, as their name has been created by replacing the _spring_ prefix with _springlets_.

The Springlets 1.x versions will be associated to the Spring IO platform Athens releases. As a result, Springlets 1.x will depend on the Spring Framework 4.3 releases. 
Also JDK 7 and 8 is supported.

== Installation and Getting Started

The Springlets libraries are released in the Maven central repository, so to use them in a Java project you just have to add them as dependencies if you use a build tool that supports it, like maven or graddle.

As an example, to add the Springlets webflow starter to a project with Maven, you would add the following dependency into the _dependencies_ section of the _pom.xml_ file:

[source,xml,indent=0]
----
<dependency>
    <groupId>io.springlets</groupId>
    <artifactId>springlets-boot-starter-webflow</artifactId>
    <version>1.0.0.RELEASE</version>
</dependency>
----

== Getting help

If you have any trouble using any of the Springlets modules:

* Report bugs with Springlets at https://github.com/DISID/springlets/issues

* As most Springlets modules provide utilities based on Spring projects, take a look at the related Spring project reference documentation. In the http://spring.io web-site you will find a lot of excellent reference documentation and getting started guides of the Spring projects.

* Ask a question in http://stackoverflow.com. The _springlets_ tag is still not available, but you can use the Spring project tag related to the Springlet module you are using.

== Reporting Issues

Springlets uses GitHub's integrated issue tracking system to record bugs and feature requests. If you want to raise an issue, please follow the recommendations below:

* Before you log a bug, please https://github.com/disid/springlets/search?type=Issues[search the issue tracker] to see if someone has already reported the problem.
* If the issue doesn't already exist, https://github.com/disid/springlets/issues/new[create a new issue].
* Please provide as much information as possible with the issue report, we like to know the version of Spring Framework or Spring Boot that you are using, as well as your Operating System and JVM version.
* If you need to paste code, or include a stack trace use Markdown +++```+++ escapes before and after your text.

== Building from Source

You don't need to build from source to use Springlets, but if you want to try out the latest and
greatest, Springlets can be easily built with the
https://github.com/takari/maven-wrapper[maven wrapper]. You also need JDK 1.7 or JDK 1.8.

[indent=0]
----
	$ ./mvnw clean install
----

If you want to build with the regular `mvn` command, you will need
http://maven.apache.org/run-maven/index.html[Maven v3.3.1 or above].

=== Project versioning

Springlets project follows the https://github.com/spring-projects/spring-build-gradle/wiki/Spring-project-versioning[Spring project versioning] best practices.

== Modules

These are main modules included in Springlets:

=== springlets-framework

It provides utilities related to the Spring Framework project. The included submodules are related to different Spring Framework modules, with configuration and utilities to:

* springlets-jms: send and receive JMS messages.
* springlets-mail: send and receive email messages.
* springlets-web: activate support for JSONP, additional Jackson properties, return BindingResults in JSON requests, build links to controllers, ...

=== springlets-data

Utilities related to the Spring Data modules. Integration of Javascript components with Spring Data commons page and sort elements.

=== springlets-security

Configuration and utilities related to Spring Security.

=== springlets-webflow

Configuration and utilities related to Spring Webflow.

=== springlets-boot-starters

Autoconfiguration starters for Spring Boot projects.

== Acknowledgments

The Springlets project uses and depends on a lot of Spring related projects, as well as other ones. We would like to thank all those projects and the people working on them, not only for the effort made to provide such excellent libraries and utilities, but also for the guidance and examples given on how to manage an open source Java project.

Also, this README.adoc file has been written based on the one included in the github.com/spring-projects/spring-boot[Spring Boot project] .

== License

Springlets is Open Source software released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
