= Springlets image:https://travis-ci.org/DISID/springlets.svg?branch=master["Build Status", link="https://travis-ci.org/DISID/springlets"]

Springlets provides a series of heterogeneus small utilities and Spring Boot starters not available in the main Spring projects: Spring Framework, Spring Data, Spring Boot, ...

== Installation and Getting Started

TODO

== Getting help
Having trouble with Springlets ? We'd like to help!

TODO

== Reporting Issues

Springlets uses GitHub's integrated issue tracking system to record bugs and feature requests. If you want to raise an issue, please follow the recommendations below:

* Before you log a bug, please https://github.com/disid/springlets/search?type=Issues[search the issue tracker] to see if someone has already reported the problem.
* If the issue doesn't already exist, https://github.com/disid/springlets/issues/new[create a new issue].
* Please provide as much information as possible with the issue report, we like to know the version of Spring Framework or Spring Boot that you are using, as well as your Operating System and JVM version.
* If you need to paste code, or include a stack trace use Markdown +++```+++ escapes before and after your text.

== Building from Source

TODO

=== Building reference documentation

TODO

== Modules

There are a number of modules in Springlets, here is a quick overview:

=== spring-boot

TODO

=== spring-data

TODO

=== spring-framework

TODO

=== spring-security

TODO

== Project versioning

Springlets project follows the https://github.com/spring-projects/spring-build-gradle/wiki/Spring-project-versioning[Spring project versioning] best practices.

== License

Springlets is Open Source software released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
