[[springlets-documentation]]
= Springlets Documentation

[partintro]
--
This section provides a brief overview of the Springlets reference documentation. 
You can read this reference guide in a linear
fashion, or you can skip sections if something doesn't interest you.
--


[[springlets-documentation-about]]
== About the documentation
// TODO: add again when the guides are available.
//The Springlets reference guide is available as {spring-boot-docs}/html[html],
//{springlets-docs}/pdf/springlets-reference.pdf[pdf]
//and {springlets-docs}/epub/springlets-reference.epub[epub] documents. The latest copy
//is available at {springlets-docs-current}.

Copies of this document may be made for your own use and for
distribution to others, provided that you do not charge any fee for such copies and
further provided that each copy contains this Copyright Notice, whether distributed in
print or electronically.


[[springlets-documentation-getting-help]]
== Getting help
If you are having trouble with the Springlets utilities, you can look for help in the following places:

* Learn the Spring basics -- Springlets builds on many other Spring projects, check
  the http://spring.io[spring.io] web-site for a wealth of reference documentation. If
  you are just starting out with Spring, try one of the Spring http://spring.io/guides[guides].
//* TODO: Ask a question - we monitor http://stackoverflow.com[stackoverflow.com] for questions
//  tagged with http://stackoverflow.com/tags/springlets[`springlets`].
* Report bugs with Springlets at https://github.com/DISID/springlets/issues .

NOTE: All of Springlets is open source, including the documentation! If you find problems
with the docs; or if you just want to improve them, please {github-code}[get involved].


[[springlets-documentation-first-steps]]
== First steps
If you're just getting started with Springlets
<<getting-started.adoc#getting-started, take a look at the Getting Started Guide>>


== Learning about Springlets features
To learn about the features provided by the Springlets libraries, just go to 
<<springlets-features.adoc#springlets-features, the Springlets features guide>>!


== Advanced topics
Lastly, we have a few topics for the more advanced user.

* *Appendix:*
<<appendix-application-properties.adoc#common-application-properties, Application Properties>> 
//|
//<<appendix-auto-configuration-classes.adoc#auto-configuration-classes, Auto-configuration classes>> |


