[[springlets-boot-features]]
== Springlets for Spring Boot features

Springlets for Spring Boot provides additional features, autoconfiguration and starters for the 
Springlets modules as well as other libraries.

The starters provided are the following ones:

[[springlets-boot-web]]
=== Springlets web starter

To use the Springlets web starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-web</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO: Pending

==== Image management

Including the Springlets web starter, the project will include all the necessary elements to manage images in the view layer. One of these elements are the `bootstrap-fileinput` jQuery plugin, that will allow developers to select and preview the images that should be uploaded to the server side. This Spring Boot starter includes the following dependencies and versions:

[source,xml,indent=0]
----
<properties>
  <bootstrap-fileinput.version>4.4.0</bootstrap-fileinput.version>
</properties>

<dependencies>
  <dependency>
    <groupId>org.webjars.bower</groupId>
    <artifactId>bootstrap-fileinput</artifactId>
    <version>${bootstrap-fileinput.version}</version>
  </dependency>
</dependencies>
----

Also, this starter includes the necessary autoconfiguration to register the `SpringletsImageFileConverter` bean (_see [[springlets-mvc-images]]_) automatically into the Spring MVC context if the `springlets.image.management` property has `true` value.


[[springlets-boot-data-jpa]]
=== Springlets Data JPA starter

To use the Springlets Data JPA starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-data-jpa</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-mail]]
=== Springlets Mail starter

To use the Springlets Mail starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-mail</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-jms]]
=== Springlets JMS starter

To use the Springlets JMS starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-jms</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-authentication]]
=== Springlets Security Authentication

To use the Springlets Security Authentication starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-authentication</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-webflow]]
=== Springlets Webflow starter

To use the Springlets Webflow starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-webflow</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-test]]
=== Springlets Test starter

To use the Springlets Tests starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-test</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



