[[springlets-data-features]]
== Springlets for Spring Data features

Springlets for Spring Data provides additional features for the following Spring 
Data modules:

* <<springlets-data-commons>>
* <<springlets-data-jpa>>

[[springlets-data-commons]]
=== Spring Data Commons

To use Springlets for the Spring Data Commons module just include the following dependency:

[source,xml,indent=0]
----
    <dependency>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-data-commons</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following utilities:

[[springlets-data-commons-datatables]]
==== Support for the Datatables javascript component

TODO


[[springlets-data-commons-select2]]
==== Support for the Select2 javascript component

TODO


[[springlets-data-commons-jaxb]]
==== Support for paging, ordering and filtering in SOAP web services

TODO

[[springlets-data-jpa]]
=== Spring Data JPA

To use Springlets for the Spring Data JPA module just include the following dependency:

[source,xml,indent=0]
----
    <dependency>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-data-jpa</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following utilities:

[[springlets-data-jpa-querydsl]]
==== Extended support for QueryDSL custom queries

TODO


[[springlets-data-jpa-detached]]
==== Support for getting a detached entity

TODO

[[springlets-data-jpa-embeddable-image]]
==== Support for image management

Springlets JPA support provides an `@Embeddable` entity to manage images as a field of an entity. To use this embeddable entity as a field of your entity, you could do it easily:

[source,java,indent=0]
----
public class MyEntity {

  @Id
  private Long id;

  @Version
  private Integer version;

  /**
   * Image field 
   */
  @Embedded
  private EmbeddableImage image;

}
----

Also, this entity provides some utility methods that will be useful to resize, format and obtain information about the stored image.

[source,java,indent=0]
----
public class MyServiceImpl implements MyService {

  @Override
  public MyEntity save(MyEntity entity){

    // Format the image to PNG format and resize it
    // to 150x150 pixels
    EmebddableImage formattedAndResizedImage = 
          entity.getImage().formatAndResize("png", 150, 150);
    
    // Obtain the format of the image
    String format = formattedAndResizedImage.getFormat();

    // Obtain the base64 value of the image
    String base64 = formattedAndResizedImage.getBase64();

    // Obtain the String representation of the
    // image. Combines getFormat() and getBase64()
    // methods.
    String imgString = formattedAndResizedImage.toString();

  }
}
----



