[[springlets-boot-features]]
== Springlets for Spring Boot features

Springlets for Spring Boot provides additional features, autoconfiguration and starters for the 
Springlets modules as well as other libraries.

The starters provided are the following ones:

[[springlets-boot-web]]
=== Springlets web starter

To use the Springlets web starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-web</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO: Pending


[[springlets-boot-data-jpa]]
=== Springlets Data JPA starter

To use the Springlets Data JPA starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-data-jpa</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-mail]]
=== Springlets Mail starter

To use the Springlets Mail starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-mail</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-jms]]
=== Springlets JMS starter

To use the Springlets JMS starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-jms</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-authentication]]
=== Springlets Security Authentication

To use the Springlets Security Authentication starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-authentication</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-webflow]]
=== Springlets Webflow starter

To use the Springlets Webflow starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-webflow</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



[[springlets-boot-test]]
=== Springlets Test starter

To use the Springlets Tests starter just include the following dependency:

[source,xml,indent=0]
----
    <dependencyT>
      <groupId>io.springlets</groupId>
      <artifactId>springlets-boot-starter-test</artifactId>
      <version>{springlets-version}</version>
    </dependency>
----

It provides the following autoconfiguration:

TODO



